plugins {
    id 'eclipse'
    id 'maven-publish'
    id 'net.neoforged.moddev' version '2.0.140'
}

version = '0.1.1-1.21.1'
group = 'com.mk2525.vsfluidlink'
archivesBaseName = 'VS-Sable-HoseConnectors'

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(21))
    }
}

compileJava {
    options.encoding = 'UTF-8'
}

neoForge {
    version = project.neoforge_version

    runs {
        client {
            client()
        }

        server {
            server()
        }
    }

    mods {
        vsfluidlink {
            sourceSet sourceSets.main
        }
    }
}

repositories {
    mavenCentral()
    maven { url = "https://maven.createmod.net" } // Create, Ponder, Flywheel
    maven { url = "https://maven.ithundxr.dev/snapshots" } // Registrate
    maven {
        name = 'tterrag maven'
        url = 'https://maven.tterrag.com/'
    }
    maven {
        url "https://www.cursemaven.com"
        content {
            includeGroup "curse.maven"
        }
    }
    // Create, Ponder, Registrate
    maven { url = "https://maven.tterrag.com/" }
    maven { url = "https://raw.githubusercontent.com/Fuzss/modresources/main/maven/" }
}

dependencies {
    // Create for NeoForge 1.21.1
    // 以前の差分で libs 内の jar を参照していたため、それに合わせます
    implementation files('libs/create-1.21.1-6.0.9.jar')
    implementation("net.createmod.ponder:ponder-neoforge:${ponder_version}+mc${minecraft_version}")
    compileOnly("dev.engine-room.flywheel:flywheel-neoforge-api-${minecraft_version}:${flywheel_version}")
    runtimeOnly("dev.engine-room.flywheel:flywheel-neoforge-${minecraft_version}:${flywheel_version}")
    implementation("com.tterrag.registrate:Registrate:${registrate_version}")
    
    // 他に必要な依存関係があればここに追加
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifactId = archivesBaseName
            from components.java
        }
    }
    repositories {
        maven {
            url "file://${project.projectDir}/local-maven"
        }
    }
}

jar {
    manifest {
        attributes([
                "Specification-Title"     : "vsHoseConnector",
                "Specification-Vendor"    : "mk2525",
                "Specification-Version"   : "1",
                "Implementation-Title"    : project.name,
                "Implementation-Version"  : project.jar.archiveVersion,
                "Implementation-Vendor"   : "mk2525",
                "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        ])
    }
}
